---
doctrine:
        dbal:
                connections:
                        default:
                                driver: "pdo_sqlite"
                                path: "%env(resolve:DB_PATH)%"
                default_connection: "default"
        orm:
                auto_mapping: false
                mappings:
                        UnlockedServer:
                                dir: "%kernel.project_dir%/config/mapping/"
                                is_bundle: false
                                prefix: "KaLehmann\\UnlockedServer\\Model"
                                type: "xml"
...
