---
monolog:
        handlers:
            main:
                formatter: "monolog.formatter.json"
                level: "debug"
                path: "php://stdout"
                type: "stream"
...
