# yamllint disable rule:line-length
---
security:
        access_control:
                api:
                        path: "^/api"
                        roles:
                                - "ROLE_CLIENT"
                maintenance:
                        path: "^/maintenance"
                        roles:
                                - "ROLE_ADMIN"
                main:
                        path: "^/.+"
                        roles:
                                - "ROLE_USER"
        firewalls:
                api:
                        custom_authenticators:
                                - "KaLehmann\\UnlockedServer\\Security\\HMACAuthenticator"
                        pattern: "^/api"
                        provider: "api_provider"
                maintenance:
                        http_basic: ~
                        pattern: "^/maintenance"
                        provider: "maintenance_users"
                main:
                        form_login:
                                check_path: "login"
                                default_target_path: "requests_list"
                                enable_csrf: true
                                login_path: "login"
                        logout:
                                path: "logout"
                        provider: "application_users"
        password_hashers:
                KaLehmann\UnlockedServer\Model\User: "auto"
                Symfony\Component\Security\Core\User\InMemoryUser: "plaintext"
        providers:
                api_provider:
                        chain:
                                providers:
                                        - 'application_clients'
                                        - 'application_users'
                application_clients:
                        entity:
                                class: 'KaLehmann\UnlockedServer\Model\Client'
                                property: "handle"
                application_users:
                        entity:
                                class: "KaLehmann\\UnlockedServer\\Model\\User"
                maintenance_users:
                        memory:
                                users:
                                        admin:
                                                password: "%env(ADMIN_PW)%"
                                                roles:
                                                        - "ROLE_ADMIN"
...
