---
security:
        access_control:
                maintenance:
                        path: "^/maintenance"
                        roles:
                                - "ROLE_ADMIN"
        firewalls:
                maintenance:
                        http_basic: ~
                        pattern: "^/maintenance"
                        provider: "maintenance_users"
        password_hashers:
                Symfony\Component\Security\Core\User\InMemoryUser: "plaintext"
        providers:
                maintenance_users:
                        memory:
                                users:
                                        admin:
                                                password: "%env(ADMIN_PW)%"
                                                roles:
                                                        - "ROLE_ADMIN"
...
