# Simple docker-compose stack for the development of the application
#
# - Services will run as non-root user.
# - The source code is always mounted to /application
# - No additional data will be shared with the host.
#   Cache files, additional dependencies and log files will be stored in
#   docker volumes.

---
version: "3.9"

x-php-service: &php_service
        build:
                args:
                        PHP_VERSION: "8.1"
                context: "."
                target: "ul_php"
        working_dir: "/application"
        volumes:
                - ".:/application"
                - "var:/application/var"
                - "vendors:/application/vendor"

services:
        composer:
                <<: *php_service
                entrypoint:
                        - "/usr/local/bin/composer"
        console:
                <<: *php_service
                entrypoint:
                        - "/usr/local/bin/php"
                        - "/application/console"
        server:
                <<: *php_service
                depends_on:
                        - "yarn"
                ports:
                        - "8000:8000"

        yarn:
                build:
                        args:
                                NODE_VERSION: "17"
                        context: "."
                        target: "ul_node"
                command:
                        - "run"
                        - "webpack"
                        - "--mode=development"
                        - "--watch"
                entrypoint:
                        - "docker-entrypoint.sh"
                        - "yarn"
                working_dir: "/application"
                volumes:
                        - ".:/application"
volumes:
        var:
        vendors:
...
