# Simple docker-compose stack for the development of the application

---
version: "3.9"

services:
        php:
                build:
                        args:
                                PHP_VERSION: "8.1"
                        context: "."
                        target: "ul_php"
                ports:
                        - "8000:8000"
                working_dir: "/application"
                volumes:
                        - ".:/application"
...
