# yamllint disable rule:line-length
---
api_request_create:
        path: '/api/requests'
        controller: 'KaLehmann\UnlockedServer\Controller\Api\RequestController::create'
        methods: 'POST'
api_request_patch:
        path: '/api/requests/{id}'
        controller: 'KaLehmann\UnlockedServer\Controller\Api\RequestController::patch'
        methods: 'PATCH'
api_request_show:
        path: '/api/requests/{id}'
        controller: 'KaLehmann\UnlockedServer\Controller\Api\RequestController::show'
        methods: 'GET'
hello:
        path: '/hello'
        controller: 'KaLehmann\UnlockedServer\Action\HelloAction'
login:
        path: '/'
        controller: 'KaLehmann\UnlockedServer\Controller\LoginController::login'
logout:
        path: '/logout'
        methods: 'GET'
keys_list:
        path: '/keys'
        controller: 'KaLehmann\UnlockedServer\Controller\KeyController::list'
maintenance_init_db:
        path: '/maintenance/init_db'
        controller: 'KaLehmann\UnlockedServer\Controller\MaintenanceController::initDb'
        methods: 'POST'
maintenance_migrate:
        path: '/maintenance/migrate'
        controller: 'KaLehmann\UnlockedServer\Controller\MaintenanceController::migrate'
        methods: 'POST'
maintenance_status:
        path: '/maintenance/status'
        controller: 'KaLehmann\UnlockedServer\Controller\MaintenanceController::status'
requests_list:
        path: '/requests'
        controller: 'KaLehmann\UnlockedServer\Controller\RequestController::list'
...
