# yamllint disable rule:line-length
---
hello:
        path: '/hello'
        controller: 'KaLehmann\UnlockedServer\Action\HelloAction'
login:
        path: '/login'
        controller: 'KaLehmann\UnlockedServer\Controller\LoginController::login'
maintenance_init_db:
        path: '/maintenance/init_db'
        controller: 'KaLehmann\UnlockedServer\Controller\MaintenanceController::initDb'
        methods: 'POST'
maintenance_migrate:
        path: '/maintenance/migrate'
        controller: 'KaLehmann\UnlockedServer\Controller\MaintenanceController::migrate'
        methods: 'POST'
maintenance_status:
        path: '/maintenance/status'
        controller: 'KaLehmann\UnlockedServer\Controller\MaintenanceController::status'
request_create:
        path: '/api/requests'
        controller: 'KaLehmann\UnlockedServer\Controller\Api\RequestController::create'
        methods: 'POST'
request_show:
        path: '/api/requests/{id}'
        controller: 'KaLehmann\UnlockedServer\Controller\Api\RequestController::show'
        methods: 'GET'
...
