# yamllint disable rule:line-length
---
api_request_create:
        path: '/api/requests'
        controller: 'KaLehmann\UnlockedServer\Controller\Api\RequestController::create'
        methods: 'POST'
api_request_patch:
        path: '/api/requests/{id}'
        controller: 'KaLehmann\UnlockedServer\Controller\Api\RequestController::patch'
        methods: 'PATCH'
api_request_show:
        path: '/api/requests/{id}'
        controller: 'KaLehmann\UnlockedServer\Controller\Api\RequestController::show'
        methods: 'GET'
clients_edit:
        path: '/clients/edit/{handle}'
        controller: 'KaLehmann\UnlockedServer\Controller\ClientController::edit'
        methods: 'GET'
clients_list:
        path: '/clients'
        controller: 'KaLehmann\UnlockedServer\Controller\ClientController::list'
        methods: 'GET'
clients_save:
        path: '/clients/edit/{handle}'
        controller: 'KaLehmann\UnlockedServer\Controller\ClientController::save'
        methods: 'POST'
hello:
        path: '/hello'
        controller: 'KaLehmann\UnlockedServer\Action\HelloAction'
login:
        path: '/'
        controller: 'KaLehmann\UnlockedServer\Controller\LoginController::login'
logout:
        path: '/logout'
        methods: 'GET'
keys_confirm_deletion:
        path: '/keys/delete/{handle}'
        controller: 'KaLehmann\UnlockedServer\Controller\KeyController::confirmDeletion'
        methods: 'GET'
keys_delete:
        path: '/keys/delete/{handle}'
        controller: 'KaLehmann\UnlockedServer\Controller\KeyController::delete'
        methods: 'POST'
keys_edit:
        path: '/keys/edit/{handle}'
        controller: 'KaLehmann\UnlockedServer\Controller\KeyController::edit'
        methods: 'GET'
keys_list:
        path: '/keys'
        controller: 'KaLehmann\UnlockedServer\Controller\KeyController::list'
        methods: 'GET'
keys_save:
        path: '/keys/edit/{handle}'
        controller: 'KaLehmann\UnlockedServer\Controller\KeyController::save'
        methods: 'POST'
maintenance_init_db:
        path: '/maintenance/init_db'
        controller: 'KaLehmann\UnlockedServer\Controller\MaintenanceController::initDb'
        methods: 'POST'
maintenance_migrate:
        path: '/maintenance/migrate'
        controller: 'KaLehmann\UnlockedServer\Controller\MaintenanceController::migrate'
        methods: 'POST'
maintenance_status:
        path: '/maintenance/status'
        controller: 'KaLehmann\UnlockedServer\Controller\MaintenanceController::status'
requests_accept:
        path: '/requests/accept'
        controller: 'KaLehmann\UnlockedServer\Controller\RequestController::accept'
requests_deny:
        path: '/requests/deny'
        controller: 'KaLehmann\UnlockedServer\Controller\RequestController::deny'
requests_list:
        path: '/requests'
        controller: 'KaLehmann\UnlockedServer\Controller\RequestController::list'
...
