# yamllint disable rule:line-length
---
hello:
        path: '/hello'
        controller: 'KaLehmann\UnlockedServer\Action\HelloAction'
maintenance_status:
        path: '/maintenance/status'
        controller: 'KaLehmann\UnlockedServer\Controller\MaintenanceController::status'
...
