---
on: "push"  # yamllint disable-line rule:truthy

jobs:
        static-analysis:
                runs-on: "ubuntu-latest"
                name: "PHPStan static analysis"
                steps:
                        - uses: "actions/checkout@v2"
                        - uses: "php-actions/composer@v6"
                        - name: "Create .env file"
                          run: |-
                                  cat << EOF > .env
                                  APP_ENV=test
                                  APP_DEBUG=0
                                  APP_SECRET=test
                                  DB_URL=sqlite3:///test.db
                                  EOF
                        - uses: "php-actions/phpstan@master"
                          with:
                                  level: "max"
                                  memory_limit: -1
                                  path: "console public/ src/"
        style-check:
                runs-on: "ubuntu-latest"
                name: "PHP CodeSniffer analysis"
                steps:
                        - uses: "actions/checkout@v2"
                        - uses: "php-actions/composer@v6"
                        - name: "PHP CodeSniffer analysis"
                          uses: "./.github/actions/code-sniffer"
                          with:
                                  path: "console public/ src/"
        yaml-analysis:
                runs-on: "ubuntu-latest"
                steps:
                        - uses: "actions/checkout@v2"
                        - name: "Set up Python"
                          uses: "actions/setup-python@v3"
                          with:
                                  python-version: "3.9"
                        - name: "Install yamllint"
                          run: "pip install yamllint"
                        - name: "Lint YAML files"
                          run: "yamllint --format=standard --strict ."
...
