---
name: "PHP CodeSniffer"
author: "Karsten Lehmann <mail@kalehmann.de>"
description: "PHP coding style analysis"
inputs:
        path:
                description: "The directories or files containing the code"
                required: true
runs:
        using: "docker"
        image: "../../../Dockerfile"
        entrypoint: "/bin/sh"
        args:
                - "-c"
                - >-
                        php vendor/bin/phpcs --standard=PSR12
                        ${{ inputs.path }}
...
