---
KaLehmann\UnlockedServer\Model\Client:
        fields:
                deleted:
                        default: false
                        nullable: false
                        type: "boolean"
                description:
                        nullable: false
                        type: "string"
                secret:
                        nullable: false
                        type: "string"
        id:
                handle:
                        type: "string"
        manyToOne:
                user:
                        joinColumn:
                                name: "user_handle"
                                referencedColumnName: "handle"
                        targetEntity: "User"
        oneToMany:
                requests:
                        mappedBy: "client"
                        targetEntity: "Request"
        repositoryClass: >-
                KaLehmann\\UnlockedServer\\Repository\\ClientRepository
        table: "clients"
        type: "entity"
...
