---
KaLehmann\UnlockedServer\Model\Key:
        fields:
                deleted:
                        default: false
                        nullable: false
                        type: "boolean"
                description:
                        nullable: false
                        type: "string"
                key:
                        nullable: false
                        type: "string"
        id:
                handle:
                        type: "string"
        manyToOne:
                user:
                        joinColumn:
                                name: "user_handle"
                                referencedColumnName: "handle"
                        targetEntity: "User"
        oneToMany:
                requests:
                        mappedBy: "key"
                        targetEntity: "Request"
        repositoryClass: "KaLehmann\\UnlockedServer\\Repository\\KeyRepository"
        table: "keys"
        type: "entity"
...
