---
KaLehmann\UnlockedServer\Model\Token:
        fields:
                description:
                        nullable: false
                        type: "string"
                expires:
                        nullable: false
                        type: "integer"
                revoked:
                        default: false
                        nullable: false
                        type: "boolean"
                token:
                        nullable: false
                        type: "string"
        id:
                id:
                        generator:
                                strategy: "AUTO"
                        type: "integer"
        manyToOne:
                user:
                        joinColumn:
                                name: "user_handle"
                                referencedColumnName: "handle"
                        targetEntity: "User"
        repositoryClass: "KaLehmann\\UnlockedServer\\Repository\\TokenRepository"
        table: "tokens"
        type: "entity"
...
